FROM ubuntu:18.04 

RUN apt-get update --fix-missing
RUN apt-get install -y nodejs 
RUN apt-get install -y npm
RUN apt-get install -y curl


COPY . .

WORKDIR /
RUN npm install -g n
RUN n stable
RUN npm install
RUN npm run build


EXPOSE 3000

# RUN SERVER
CMD ["npm", "start"]