FROM ubuntu:18.04 

RUN apt-get update --fix-missing
RUN apt-get install -y python3-pip 

COPY . .

RUN pip3 install wheel
RUN pip3 install -r requirements.txt

EXPOSE 5000

# RUN SERVER
CMD ["python3", "run.py"]